/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ifrmCadEstadodoLivro.java
 *
 * Created on 16/09/2010, 22:49:54
 */
package FormsdeConfiguracao;

import Classes2.EstadoDoLivro;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashSet;
import javax.swing.JOptionPane;
import Classes.DB;
import Classes.FixedLengthDocument;
import Classes.Funcoes;
import Classes.Query;

/**
 *
 * @author MARK
 */
public class ifrmConfiguracoes extends javax.swing.JInternalFrame {

    private boolean novoCadastro;
    private EstadoDoLivro estado;
    private DB banco;
    private Funcoes f;

    /** Creates new form ifrmCadEstadodoLivro */
    public ifrmConfiguracoes() {

        initComponents();
        txtDiasEmprestimo.setDocument(new FixedLengthDocument(3));
        txtDiasReserva.setDocument(new FixedLengthDocument(3));
        txtDiasRenovacao.setDocument(new FixedLengthDocument(3));


        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpEmprestimos = new javax.swing.JPanel();
        txtDiasEmprestimo = new javax.swing.JTextField();
        txtQtdEmprestimos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpRenovacoes = new javax.swing.JPanel();
        txtDiasRenovacao = new javax.swing.JTextField();
        txtQtdRenovacoes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpReservas = new javax.swing.JPanel();
        txtDiasReserva = new javax.swing.JTextField();
        txtQtdReservas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Configurações Gerais");
        setMaximumSize(new java.awt.Dimension(384, 336));
        setMinimumSize(new java.awt.Dimension(384, 336));
        setNormalBounds(new java.awt.Rectangle(0, 0, 690, 542));
        setPreferredSize(new java.awt.Dimension(384, 336));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Adicionar.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar");
        btnAdicionar.setFocusable(false);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setPreferredSize(new java.awt.Dimension(24, 24));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdicionar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Editar.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(false);

        jLabel1.setText("Código:");

        jpEmprestimos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Empréstimos"));

        jLabel2.setText("Dias:");

        jLabel3.setText("Quantidade de Empréstimos:");

        javax.swing.GroupLayout jpEmprestimosLayout = new javax.swing.GroupLayout(jpEmprestimos);
        jpEmprestimos.setLayout(jpEmprestimosLayout);
        jpEmprestimosLayout.setHorizontalGroup(
            jpEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmprestimosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiasEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpEmprestimosLayout.setVerticalGroup(
            jpEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEmprestimosLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jpEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiasEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtdEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jpRenovacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Renovações"));

        jLabel6.setText("Dias:");

        jLabel7.setText("Quantidade de Renovações:");

        javax.swing.GroupLayout jpRenovacoesLayout = new javax.swing.GroupLayout(jpRenovacoes);
        jpRenovacoes.setLayout(jpRenovacoesLayout);
        jpRenovacoesLayout.setHorizontalGroup(
            jpRenovacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRenovacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiasRenovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdRenovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpRenovacoesLayout.setVerticalGroup(
            jpRenovacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRenovacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRenovacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiasRenovacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtQtdRenovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpReservas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reservas"));

        jLabel4.setText("Dias:");

        jLabel5.setText("Quantidade de Reservas:");

        javax.swing.GroupLayout jpReservasLayout = new javax.swing.GroupLayout(jpReservas);
        jpReservas.setLayout(jpReservasLayout);
        jpReservasLayout.setHorizontalGroup(
            jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpReservasLayout.setVerticalGroup(
            jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReservasLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtQtdReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpRenovacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRenovacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-396)/2, (screenSize.height-336)/2, 396, 336);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Botões
        btnAdicionar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        //Ativa os campos
        f = new Funcoes();
        f.ativarCampos(jpEmprestimos, true);
        f.ativarCampos(jpReservas, true);
        f.ativarCampos(jpRenovacoes, true);
        txtDiasEmprestimo.requestFocus();

        //===========================================================
        //cria um objeto MysqlDB apontando para o banco especificado.
        banco = new DB();
        banco.connect();
        int max1 = -1;

        //conecta ao banco
        Query query1 = new Query(banco.conn);
        //Cria um objeto do tipo query chamado query1 que recebe
        //como argumento o  objeto banco.

        try {
            String sql = " SELECT MAX(codigo) FROM configuracoes";
            query1.open(sql); //executa uma sentença sql.
            query1.next();

            max1 = query1.rs.getInt(1);

            banco.disconnect();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:" + e.getMessage());
//        } finally {
            try {
                query1.rs.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro resultset: " + ex.getMessage());
            }
        }

        txtCodigo.setText(String.valueOf(max1 + 1));

        novoCadastro = true;

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        btnAdicionar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);

        f.ativarCampos(jpEmprestimos, true);
        f.ativarCampos(jpReservas, true);
        f.ativarCampos(jpRenovacoes, true);
        txtDiasEmprestimo.requestFocus();

        novoCadastro = false;
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        f = new Funcoes();
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        f.ativarCampos(jpEmprestimos, false);
        f.ativarCampos(jpReservas, false);
        f.ativarCampos(jpRenovacoes, false);       

        //ao cancelar verifica se tem algum registro no banco e retorna os dados
        banco = new DB();
        banco.connect();
        Query q = new Query(banco.conn);
        q.open("SELECT codigo,diasdoemprestimo,qtdemprestimos,diasdareserva,"
                + "qtdreservas,diasdarenovacao,qtdrenovacoes FROM configuracoes");
        q.next();
        String codigo, diasdoemprestimo, qtdemprestimos, diasdareserva,
                qtdreservas, diasdarenovacao, qtdrenovacoes;
        codigo = q.fieldbyname("codigo");
        diasdoemprestimo = q.fieldbyname("diasdoemprestimo");
        qtdemprestimos = q.fieldbyname("qtdemprestimos");
        diasdareserva = q.fieldbyname("diasdareserva");
        qtdreservas = q.fieldbyname("qtdreservas");
        diasdarenovacao = q.fieldbyname("diasdarenovacao");
        qtdrenovacoes = q.fieldbyname("qtdrenovacoes");

        txtCodigo.setText(codigo);
        txtDiasEmprestimo.setText(diasdoemprestimo);
        txtQtdEmprestimos.setText(qtdemprestimos);
        txtDiasReserva.setText(diasdareserva);
        txtQtdReservas.setText(qtdreservas);
        txtDiasRenovacao.setText(diasdarenovacao);
        txtQtdRenovacoes.setText(qtdrenovacoes);

        //verifica se possui dados 
         if (!txtCodigo.getText().trim().equals("")) {
            btnAdicionar.setEnabled(false);
            btnEditar.setEnabled(true);
        } else {
            btnAdicionar.setEnabled(true);
            btnEditar.setEnabled(false);
        }

        novoCadastro = false;
}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (txtDiasEmprestimo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de dias que "
                    + "pode ser emprestado!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            txtDiasEmprestimo.requestFocus();
        } else if (txtQtdEmprestimos.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de obras "
                    + "que podem ser emprestadas!",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtdEmprestimos.requestFocus();
        } else if (txtDiasReserva.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de dias "
                    + "que pode ser reservado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtDiasReserva.requestFocus();
        } else if (txtQtdReservas.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de obras "
                    + "que podem ser reservadas!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtdReservas.requestFocus();
        } else if (txtDiasRenovacao.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de dias "
                    + "que pode ser renovado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtDiasRenovacao.requestFocus();
        } else if (txtQtdRenovacoes.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade de obras "
                    + "que podem ser renovadas!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtdRenovacoes.requestFocus();
        } //Insert
        else if (novoCadastro == true) {
            //cria um objeto DB apontando para o banco especificado.
            banco = new DB();
            //conecta ao banco
            banco.connect();
            //Variavel para verificar se foi executado o comando
            int ri = 0;
            //Insere usando formatacao JAVA
            PreparedStatement st1 = null;
            String sqlInsert = "INSERT INTO cadestadodolivro(codigo,diasdoemprestimo,qtdemprestimos,diasdareserva,"
                    + "qtdreservas,diasdarenovacao,qtdrenovacoes)VALUES(?,?,?,?,?,?,?)";
            try {
                st1 = banco.conn.prepareStatement(sqlInsert);
                st1.setInt(1, Integer.parseInt(txtCodigo.getText().trim()));
                st1.setInt(2, Integer.parseInt(txtDiasEmprestimo.getText().trim()));
                st1.setInt(3, Integer.parseInt(txtQtdEmprestimos.getText().trim()));
                st1.setInt(4, Integer.parseInt(txtDiasReserva.getText().trim()));
                st1.setInt(5, Integer.parseInt(txtQtdReservas.getText().trim()));
                st1.setInt(6, Integer.parseInt(txtDiasRenovacao.getText().trim()));
                st1.setInt(7, Integer.parseInt(txtQtdRenovacoes.getText().trim()));
                ri = st1.executeUpdate();
                st1.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao adicionar! \n" + e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            if (ri > 0) {
                JOptionPane.showMessageDialog(null, "Registro adicionado"
                        + " com sucesso !", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                btnAdicionar.setEnabled(false);
                btnEditar.setEnabled(true);
                btnCancelar.setEnabled(false);
                btnSalvar.setEnabled(false);
                f.ativarCampos(jpEmprestimos, false);
                f.ativarCampos(jpReservas, false);
                f.ativarCampos(jpRenovacoes, false);
            }
        } //senão Update
        else if (novoCadastro == false) {
            //cria um objeto DB apontando para o banco especificado.
            banco = new DB();
            banco.connect();
            //conecta ao banco
            int ru = 0;
            //Atualiza usando formatacao JAVA
            PreparedStatement st1 = null;
            String sqlInsert = "UPDATE configuracoes SET diasdoemprestimo=?,"
                    + "qtdemprestimos=?,diasdareserva=?,qtdreservas=?,diasdarenovacao=?,"
                    + "qtdrenovacoes=? WHERE codigo=?";
            try {
                st1 = banco.conn.prepareStatement(sqlInsert);
                st1.setInt(1, Integer.parseInt(txtDiasEmprestimo.getText().trim()));
                st1.setInt(2, Integer.parseInt(txtQtdEmprestimos.getText().trim()));
                st1.setInt(3, Integer.parseInt(txtDiasReserva.getText().trim()));
                st1.setInt(4, Integer.parseInt(txtQtdReservas.getText().trim()));
                st1.setInt(5, Integer.parseInt(txtDiasRenovacao.getText().trim()));
                st1.setInt(6, Integer.parseInt(txtQtdRenovacoes.getText().trim()));
                st1.setInt(7, Integer.parseInt(txtCodigo.getText().trim()));
                ru = st1.executeUpdate();
                st1.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            if (ru > 0) {
                JOptionPane.showMessageDialog(null, "Registro atualizado "
                        + "com sucesso !", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                btnAdicionar.setEnabled(false);
                btnEditar.setEnabled(true);
                btnCancelar.setEnabled(false);
                btnSalvar.setEnabled(false);
                f.ativarCampos(jpEmprestimos, false);
                f.ativarCampos(jpReservas, false);
                f.ativarCampos(jpRenovacoes, false);

            }
        }

}//GEN-LAST:event_btnSalvarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        txtCodigo.setVisible(false);
        jLabel1.setVisible(false);

        btnCancelarActionPerformed(null);

    }//GEN-LAST:event_formInternalFrameOpened
// Check for key codes. if (evt.getKeyCode() == KeyEvent.VK_HOME) { process(evt.getKeyCode()); }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jpEmprestimos;
    private javax.swing.JPanel jpRenovacoes;
    private javax.swing.JPanel jpReservas;
    public javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDiasEmprestimo;
    private javax.swing.JTextField txtDiasRenovacao;
    private javax.swing.JTextField txtDiasReserva;
    private javax.swing.JTextField txtQtdEmprestimos;
    private javax.swing.JTextField txtQtdRenovacoes;
    private javax.swing.JTextField txtQtdReservas;
    // End of variables declaration//GEN-END:variables
}
