/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ifrmAparencia.java
 *
 * Created on 21/12/2010, 09:53:25
 */
package FormsdeConfiguracao;

import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.HashSet;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import Forms.frmMenu;

/**
 *
 * @author MARK
 */
public class ifrmAparencia extends javax.swing.JInternalFrame {

    /** Creates new form ifrmAparencia */
    public ifrmAparencia() {

        //initialize();
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbAparencia = new javax.swing.JComboBox();
        btnAplicar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Aparência do programa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o estilo visual para todo o programa"));

        cbAparencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Metal", "Nimbus", "CDE/Motif", "Windows", "Windows Classic", "Liquid" }));

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbAparencia, 0, 342, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(6, 6, 6)
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAplicar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAparencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicar)
                    .addComponent(btnCancelar)
                    .addComponent(btnVisualizar))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-410)/2, (screenSize.height-242)/2, 410, 242);
    }// </editor-fold>//GEN-END:initComponents

    //Ler arquivo texto da Aparência
    //Ler arquivo texto
    private String LF() {
        String look = null;
        try {
            FileReader reader = new FileReader(new File("look.txt"));
            BufferedReader leitor = new BufferedReader(reader);

            //Lê linha por linha \n quebra a linha
//            leitor.readLine().substring(8);
//            leitor.readLine().substring(12);
//            leitor.readLine().substring(12);
            look = leitor.readLine();

            //Fecha a leitura
            reader.close();
            leitor.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return look;
    }

//Grava no arquivo texto
    private String EscreveLF(String look) {


        try {
            // o true significa q o arquivo será constante
            FileWriter x = new FileWriter("look.txt", false);


//         look += "\n\n\n\r"; // criando nova linha e recuo no arquivo
            x.write(look); // armazena o texto no objeto x, que aponta para o arquivo
            x.close(); // cria o arquivo
            JOptionPane.showMessageDialog(null, "Aparência alterada com sucesso !", "Concluído", JOptionPane.INFORMATION_MESSAGE);
        } // em caso de erro apreenta mensagem abaixo
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return look;
    }

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
//Verifica qual o usuário quer e grava no config.txt
        //[Look]
        try {
            String Look = null;
            if (cbAparencia.getSelectedIndex() == 0) {
                //Metal
                Look = "javax.swing.plaf.metal.MetalLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 1) {
                //Nimbus
                Look = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 2) {
                //CDE/Motif
                Look = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 3) {
                //Windows
                Look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 4) {
                //Windows classic
                Look = "com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 5) {
                //Liquid
                Look = "com.birosoft.liquid.LiquidLookAndFeel";
            }
            //Escreve no config.txt o nome do LookAndFeel usado
            EscreveLF(Look);
            javax.swing.UIManager.setLookAndFeel(LF());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        try {
            String LookPreview = null;
            if (cbAparencia.getSelectedIndex() == 0) {
                //Metal
                LookPreview = "javax.swing.plaf.metal.MetalLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 1) {
                //Nimbus
                LookPreview = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 2) {
                //CDE/Motif
                LookPreview = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 3) {
                //Windows
                LookPreview = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 4) {
                //Windows classic
                LookPreview = "com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel";
            } else if (cbAparencia.getSelectedIndex() == 5) {
                //Liquid
                LookPreview = "com.birosoft.liquid.LiquidLookAndFeel";
            }
            javax.swing.UIManager.setLookAndFeel(LookPreview);
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            frmMenu fr = new frmMenu();
          javax.swing.SwingUtilities.updateComponentTreeUI(fr);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox cbAparencia;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
