/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * testePermissoesComjTree.java
 *
 * Created on 24/02/2012, 17:54:34
 */

package Testes;

import java.awt.Component;
import javax.swing.JCheckBox;



import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MARK
 */
public class testePermissoesComjTree extends javax.swing.JFrame {

    /** Creates new form testePermissoesComjTree */
    public testePermissoesComjTree() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 405, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        //Mudar o ícone da árvore
        //DefaultTreeCellRenderer render= (DefaultTreeCellRenderer)jTree1.getCellRenderer();
        //render.setLeafIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/AbrirArquivo.png")));
        //render.setOpenIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/aberto.png")));
        //render.setClosedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/fechado.png")));
        //Pai
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("--------------------Permissões--------------------");
        //Grupo
        DefaultMutableTreeNode grupo = null;
        //Login-----------------------------------------------------------------
        grupo = new DefaultMutableTreeNode("Login");
        //Adiciona o grupo à raiz
        raiz.add(grupo);
        //Adiciona os filhos ao grupo
        grupo.add(new DefaultMutableTreeNode("Cadastro de Login"));
        grupo.add(new DefaultMutableTreeNode("Cadastro de Níveis e Permissões"));
        //----------------------------------------------------------------------
        grupo = new DefaultMutableTreeNode("Cadastros");
        //Adiciona o grupo à raiz
        raiz.add(grupo);
        //Adiciona os filhos ao grupo
        grupo.add(new DefaultMutableTreeNode("Acervo da Biblioteca"));
        grupo.add(new DefaultMutableTreeNode("Biblioteca"));
        //----------------------------------------------------------------------

        //----------------------------------------------------------------------

        //----------------------------------------------------------------------

        //----------------------------------------------------------------------
        DefaultTreeModel treeModel = new DefaultTreeModel(raiz);
        //Seta o modelo
        jTree1.setModel(treeModel);
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testePermissoesComjTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
