/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteImagemdeFundo.java
 *
 * Created on 30/03/2011, 15:08:44
 */
package Testes;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author MARK
 */
public class TesteImagemdeFundo extends javax.swing.JFrame {

    private Image img;
    private File Nomeimagem;
    private javax.swing.JLabel lblImagem = new javax.swing.JLabel();

    /** Creates new form TesteImagemdeFundo */
    public TesteImagemdeFundo() {

        initComponents();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        txtCaminho = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtCaminho.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnProcurar.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Digite o caminho da imagem ou selecione o caminho");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtCaminho, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnProcurar)
                    .add(jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnCancelar)
                        .add(6, 6, 6)
                        .add(btnVisualizar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtCaminho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnProcurar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnOk)
                    .add(btnCancelar)
                    .add(btnVisualizar))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (!txtCaminho.getText().trim().equals("")) {
            // Escreve a imagem gerada para um arquivo
            try {     
                BufferedImage image = ImageIO.read(Nomeimagem);
//                image.getScaledInstance(this.getWidth(), this.getHeight(), 10000);
                // Salva como JPEG
                File file = new File("Imagem.jpg");
                ImageIO.write( image, "JPG", file);
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
}//GEN-LAST:event_btnOkActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        javax.swing.JFileChooser jfc = new javax.swing.JFileChooser(new File("FotodosLeitores/"), FileSystemView.getFileSystemView());
        jfc.setMultiSelectionEnabled(false);
        jfc.setDialogTitle("Selecione a foto do leitor");
        jfc.setFileFilter(new FileNameExtensionFilter("JPG, GIF e PNG", "jpg", "gif", "png"));
        //      this.lblFoto.setText("");
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);// ha outras opcoes alem de files_only
        int resposta = jfc.showOpenDialog(this);
        if (resposta == 0) {
            Nomeimagem = jfc.getSelectedFile();
            // se clica em carregar imagem faz isso...
 img = new ImageIcon(jfc.getSelectedFile().getAbsolutePath()).getImage().getScaledInstance(this.getWidth(),this.getHeight(),10000);
//            img = new ImageIcon(jfc.getSelectedFile().getAbsolutePath()).getImage();
            txtCaminho.setText(Nomeimagem.getAbsolutePath());
        }
}//GEN-LAST:event_btnProcurarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
//frmMenuTESTE menu= new frmMenuTESTE();
        if (Nomeimagem != null && Nomeimagem.exists()) {
            lblImagem.setIcon(new ImageIcon(img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT)));
            lblImagem.setVisible(true);
            lblImagem.setSize(this.getSize());
            this.getContentPane().add(lblImagem);
            this.repaint();
//        menu.caminhoImagemFundo=txtCaminho.getText().trim();
//        menu.visualizacao=true;
        }
        else if (Nomeimagem == null) {
            JOptionPane.showMessageDialog(null, "Selecione uma imagem", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if (Nomeimagem.exists() == false) {
            JOptionPane.showMessageDialog(null, "A imagem não existe", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TesteImagemdeFundo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
