/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmMenu.java
 *
 * Created on 20/08/2010, 23:36:52
 */
package Forms;

import FormsAjuda.ifrmSobreoSistema;
import FormsMovimento.ifrmDevolucao;
import FormsMovimento.ifrmEmprestimo;
import FormsMovimento.ifrmRenovacao;
import FormsMovimento.ifrmReserva;
import FormsRelatorio.ifrmCarteirinhadoLeitor;
import FormsRelatorio.ifrmEtiquetascomCodigodeBarras;
import FormsRelatorio.ifrmRelatorioEmprestimos;
import FormsRelatorio.ifrmRelatorioLeituraNoLocal;
import FormsRelatorio.ifrmRelatorioTitulosMaisEmprestados;
import FormsRelatorio.ifrmRelatorioTitulosMaisLidos;
import FormsdeCadastro.ifrmCadBairros;
import FormsdeCadastro.ifrmCadCidades;
import FormsdeCadastro.ifrmCadEstadodoLivro;
import FormsdeCadastro.ifrmCadFormacaoAcademica;
import FormsdeCadastro.ifrmCadNiveldeEscolaridade;
import FormsdeCadastro.ifrmCadTipodeFormacao;
import FormsdeConfiguracao.ifrmAparencia;
import FormsdeConfiguracao.ifrmConfiguracoes;
import FormsdeConfiguracao.ifrmImagemdeFundo;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import Classes.DB;
import Classes.Query;
import FormsRelatorio.ifrmRelatorioObras;
import FormsdeConfiguracao.ifrmBackup;
import FormsdeConfiguracao.ifrmRestaurarBackup;
import login.frmLogin;
import login.ifrmCadLogin;
import login.ifrmCadNiveis;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARK
 */
public class frmMenu extends javax.swing.JFrame {
//*****************************************************************************
    //Variáveis públicas para serem lidas pelo menu

    public boolean cadlogin1 = false,
            cadniveis = false,
            cadcategoriadoleitor = false,
            cadacervo = false,
            cadautores = false,
            cadbiblioteca = false,
            cadclasliteraria = false,
            cadeditora = false,
            cadgrupo = false,
            cadidioma = false,
            cadestadodeconservacao = false,
            cadleitor = false,
            cadformacaoacademica = false,
            cadniveldeescolaridade = false,
            cadtipodeformacao = false,
            cadcidade = false,
            cadbairro = false,
            movemprestimo = false,
            movdevolucao = false,
            movrenovacao = false,
            movreserva = false,
            relautores = false,
            relclasliterarias = false,
            releditoras = false,
            relgrupos = false,
            relleitores = false,
            relleituras = false,
            relemprestimos = false,
            reltitulosmaislidos = false,
            reltitulosmaisemprestados = false,
            relcarteirinhadoleitor = false,
            reletiquetasdasobras1 = false,
            relobrasdoacervo = false,
            confconfiguracoesgerais = false,
            confbackup = false,
            confrestaurarbackup = false,
            confmudaraparencia = false,
            confimagemdefundodomenu = false,
            ajconteudo = false;
    
    //PARA A IMAGEM DE FUNDO====================================================
    private Image imagemFundo = null;
    private javax.swing.JLabel lblImagem = new javax.swing.JLabel();
//VERIFICA SE É SÓ VISUALIZAÇÃO OU NÃO
    public boolean visualizacao = false;
//CAMINHO DA IMAGEM
    public String caminhoImagemFundo = null;
    java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
    java.awt.Dimension screenSize = tk.getScreenSize();
 
    /** Creates new form frmMenu */
    public frmMenu() {       

        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("Livro24x24.png");
        setIconImage(img);

        initComponents();

        //Seta o Look And Feel padrão
        try {
            try {
                javax.swing.UIManager.setLookAndFeel(LF());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Aviso", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
            }
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Aviso", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuLogin = new javax.swing.JMenu();
        MenuLoginLogout = new javax.swing.JMenuItem();
        MenuLoginCadastrarLogin = new javax.swing.JMenuItem();
        MenuLoginCadastrarNiveis = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadItens = new javax.swing.JMenuItem();
        MenuCadCategoriadoLeitor = new javax.swing.JMenuItem();
        MenuCadAutor = new javax.swing.JMenuItem();
        MenuCadBiblioteca = new javax.swing.JMenuItem();
        MenuCadClasLiterarias = new javax.swing.JMenuItem();
        MenuCadEditoras = new javax.swing.JMenuItem();
        MenuCadGrupos = new javax.swing.JMenuItem();
        MenuCadIdiomas = new javax.swing.JMenuItem();
        MenuCadEstadodoLivro = new javax.swing.JMenuItem();
        MenuCadLeitores = new javax.swing.JMenuItem();
        MenuCadFormacaoAcademica = new javax.swing.JMenuItem();
        MenuCadNiveldeEscolaridade = new javax.swing.JMenuItem();
        MenuCadTipodeFormacao = new javax.swing.JMenuItem();
        MenuCadCidades = new javax.swing.JMenuItem();
        MenuCadBairros = new javax.swing.JMenuItem();
        MenuMovimentacao = new javax.swing.JMenu();
        MenuMovimentoEmprestimo = new javax.swing.JMenuItem();
        MenuMovimentoDevolucao = new javax.swing.JMenuItem();
        MenuMovimentoRenovacao = new javax.swing.JMenuItem();
        MenuMovimentoReserva = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        MenuRelatorioAutores = new javax.swing.JMenuItem();
        MenuRelatorioClasLiterarias = new javax.swing.JMenuItem();
        MenuRelatorioEditoras = new javax.swing.JMenuItem();
        MenuRelatorioGrupos = new javax.swing.JMenuItem();
        MenuRelatorioLeitores = new javax.swing.JMenuItem();
        MenuRelatorioLeituras = new javax.swing.JMenuItem();
        MenuRelatorioEmprestimos = new javax.swing.JMenuItem();
        MenuRelatorioTitulosMaisLidos = new javax.swing.JMenuItem();
        MenuRelatorioTitulosMaisEmprestados = new javax.swing.JMenuItem();
        MenuRelatorioCarteirinhaLeitor = new javax.swing.JMenuItem();
        MenuRelatorioCodigodeBarrasdasObras = new javax.swing.JMenuItem();
        MenuRelatorioObras = new javax.swing.JMenuItem();
        MenuConfig = new javax.swing.JMenu();
        MenuConfigConfiguracoes = new javax.swing.JMenuItem();
        MenuConfigBackup = new javax.swing.JMenuItem();
        MenuConfigRestaurarBackup = new javax.swing.JMenuItem();
        MenuConfigAparencia = new javax.swing.JMenuItem();
        MenuConfigImagemdeFundo = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuAjudaConteudo = new javax.swing.JMenuItem();
        MenuAjudaSobreoSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para Gerenciamento de Bibliotecas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desktopPaneMouseClicked(evt);
            }
        });

        MenuLogin.setText("Login");

        MenuLoginLogout.setText("Logout");
        MenuLoginLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginLogoutActionPerformed(evt);
            }
        });
        MenuLogin.add(MenuLoginLogout);

        MenuLoginCadastrarLogin.setText("Cadastrar Login");
        MenuLoginCadastrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginCadastrarLoginActionPerformed(evt);
            }
        });
        MenuLogin.add(MenuLoginCadastrarLogin);

        MenuLoginCadastrarNiveis.setText("Cadastrar Nível e Permissões do Usuário");
        MenuLoginCadastrarNiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginCadastrarNiveisActionPerformed(evt);
            }
        });
        MenuLogin.add(MenuLoginCadastrarNiveis);

        menuBar.add(MenuLogin);

        MenuCadastro.setText("Cadastros");

        MenuCadItens.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuCadItens.setText("Acervo da biblioteca");
        MenuCadItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadItensActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadItens);

        MenuCadCategoriadoLeitor.setText("Categoria do Leitor");
        MenuCadastro.add(MenuCadCategoriadoLeitor);

        MenuCadAutor.setText("Autores");
        MenuCadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadAutorActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadAutor);

        MenuCadBiblioteca.setText("Biblioteca");
        MenuCadBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadBibliotecaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadBiblioteca);

        MenuCadClasLiterarias.setText("Classificações Literárias");
        MenuCadClasLiterarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadClasLiterariasActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadClasLiterarias);

        MenuCadEditoras.setText("Editoras");
        MenuCadEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadEditorasActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadEditoras);

        MenuCadGrupos.setText("Grupos");
        MenuCadGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadGruposActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadGrupos);

        MenuCadIdiomas.setText("Idiomas");
        MenuCadIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadIdiomasActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadIdiomas);

        MenuCadEstadodoLivro.setText("Estado de Conservação");
        MenuCadEstadodoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadEstadodoLivroActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadEstadodoLivro);

        MenuCadLeitores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuCadLeitores.setText("Leitores");
        MenuCadLeitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadLeitoresActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadLeitores);

        MenuCadFormacaoAcademica.setText("Formação Acadêmica");
        MenuCadFormacaoAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadFormacaoAcademicaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadFormacaoAcademica);

        MenuCadNiveldeEscolaridade.setText("Nível de Escolaridade");
        MenuCadNiveldeEscolaridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadNiveldeEscolaridadeActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadNiveldeEscolaridade);

        MenuCadTipodeFormacao.setText("Tipo de Formação");
        MenuCadTipodeFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadTipodeFormacaoActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadTipodeFormacao);

        MenuCadCidades.setText("Cidades");
        MenuCadCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadCidadesActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadCidades);

        MenuCadBairros.setText("Bairros");
        MenuCadBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadBairrosActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadBairros);

        menuBar.add(MenuCadastro);

        MenuMovimentacao.setText("Movimentação");

        MenuMovimentoEmprestimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MenuMovimentoEmprestimo.setText("Empréstimo");
        MenuMovimentoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMovimentoEmprestimoActionPerformed(evt);
            }
        });
        MenuMovimentacao.add(MenuMovimentoEmprestimo);

        MenuMovimentoDevolucao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        MenuMovimentoDevolucao.setText("Devolução");
        MenuMovimentoDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMovimentoDevolucaoActionPerformed(evt);
            }
        });
        MenuMovimentacao.add(MenuMovimentoDevolucao);

        MenuMovimentoRenovacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        MenuMovimentoRenovacao.setText("Renovação");
        MenuMovimentoRenovacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMovimentoRenovacaoActionPerformed(evt);
            }
        });
        MenuMovimentacao.add(MenuMovimentoRenovacao);

        MenuMovimentoReserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        MenuMovimentoReserva.setText("Reserva");
        MenuMovimentoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMovimentoReservaActionPerformed(evt);
            }
        });
        MenuMovimentacao.add(MenuMovimentoReserva);

        menuBar.add(MenuMovimentacao);

        MenuRelatorios.setText("Relatórios");

        MenuRelatorioAutores.setText("Relação dos Autores");
        MenuRelatorioAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioAutoresActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioAutores);

        MenuRelatorioClasLiterarias.setText("Relação das Classificações Literárias");
        MenuRelatorioClasLiterarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioClasLiterariasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioClasLiterarias);

        MenuRelatorioEditoras.setText("Relação das Editoras");
        MenuRelatorioEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioEditorasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioEditoras);

        MenuRelatorioGrupos.setText("Relação dos Grupos");
        MenuRelatorioGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioGruposActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioGrupos);

        MenuRelatorioLeitores.setText("Relação Geral de Leitores");
        MenuRelatorioLeitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioLeitoresActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioLeitores);

        MenuRelatorioLeituras.setText("Relação de Leituras");
        MenuRelatorioLeituras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioLeiturasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioLeituras);

        MenuRelatorioEmprestimos.setText("Relação de Empréstimos");
        MenuRelatorioEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioEmprestimosActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioEmprestimos);

        MenuRelatorioTitulosMaisLidos.setText("Títulos Mais Lidos");
        MenuRelatorioTitulosMaisLidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioTitulosMaisLidosActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioTitulosMaisLidos);

        MenuRelatorioTitulosMaisEmprestados.setText("Títulos Mais Emprestados");
        MenuRelatorioTitulosMaisEmprestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioTitulosMaisEmprestadosActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioTitulosMaisEmprestados);

        MenuRelatorioCarteirinhaLeitor.setText("Carteirinha do Leitor");
        MenuRelatorioCarteirinhaLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioCarteirinhaLeitorActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioCarteirinhaLeitor);

        MenuRelatorioCodigodeBarrasdasObras.setText("Etiquetas com Código de barras das Obras");
        MenuRelatorioCodigodeBarrasdasObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioCodigodeBarrasdasObrasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioCodigodeBarrasdasObras);

        MenuRelatorioObras.setText("Obras do Acervo");
        MenuRelatorioObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioObrasActionPerformed(evt);
            }
        });
        MenuRelatorios.add(MenuRelatorioObras);

        menuBar.add(MenuRelatorios);

        MenuConfig.setText("Configurações");

        MenuConfigConfiguracoes.setText("Configurações Gerais");
        MenuConfigConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfigConfiguracoesActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuConfigConfiguracoes);

        MenuConfigBackup.setText("Backup");
        MenuConfigBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfigBackupActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuConfigBackup);

        MenuConfigRestaurarBackup.setText("Restaurar Backup");
        MenuConfigRestaurarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfigRestaurarBackupActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuConfigRestaurarBackup);

        MenuConfigAparencia.setText("Mudar Aparência");
        MenuConfigAparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfigAparenciaActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuConfigAparencia);

        MenuConfigImagemdeFundo.setText("Imagem de Fundo do Menu");
        MenuConfigImagemdeFundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConfigImagemdeFundoActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuConfigImagemdeFundo);

        menuBar.add(MenuConfig);

        MenuAjuda.setText("Ajuda");

        MenuAjudaConteudo.setText("Conteúdo");
        MenuAjuda.add(MenuAjudaConteudo);

        MenuAjudaSobreoSistema.setText("Sobre o Sistema...");
        MenuAjudaSobreoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudaSobreoSistemaActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuAjudaSobreoSistema);

        menuBar.add(MenuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        setBounds(0, 0, 536, 405);
    }// </editor-fold>//GEN-END:initComponents

//Abrir tela InternalFrame
    public void abrirTela(Class classe) {

        //Verificando se a janela está aberta.
        for (int i = 0; i < this.desktopPane.getAllFrames().length; i++) {
            if (this.desktopPane.getAllFrames()[i].getClass().getName().equals(
                    classe.getName())) {
                this.desktopPane.getAllFrames()[i].toFront();
                return;
            }
        }
        JInternalFrame iFrame;
        try {
            iFrame = ((JInternalFrame) classe.newInstance());
            this.desktopPane.add(iFrame);
            iFrame.show();
            iFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Livro24x24.png")));
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        }
        //Seta o Look And Feel padrão
        try {
            try {
                javax.swing.UIManager.setLookAndFeel(LF());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Aviso", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
            }
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Aviso", ex.getMessage(), JOptionPane.WARNING_MESSAGE);
        }
    }

    //Ler arquivo texto da Aparência
    //Ler arquivo texto
    private String LF() {
        String look = null;
        try {
            FileReader reader = new FileReader(new File("look.txt"));
            BufferedReader leitor = new BufferedReader(reader);
            //Lê linha por linha \n quebra a linha
            look = leitor.readLine();
            //Fecha a leitura
            reader.close();
            leitor.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return look;
    }

    //Ler arquivo texto
    private String CaminhodoRelatorio() {
        String caminho = null;
        try {
            FileReader reader = new FileReader(new File("config.txt"));
            BufferedReader leitor = new BufferedReader(reader);

            //Lê linha por linha \n quebra a linha
            leitor.readLine().substring(8);
            leitor.readLine().substring(12);
            caminho = leitor.readLine().substring(12);

            //Fecha a leitura
            reader.close();
            leitor.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return caminho;
    }

    private void MenuCadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadAutorActionPerformed
        abrirTela(new ifrmCadAutores().getClass());
    }//GEN-LAST:event_MenuCadAutorActionPerformed

    private void MenuCadItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadItensActionPerformed
        abrirTela(new ifrmCadItens().getClass());
    }//GEN-LAST:event_MenuCadItensActionPerformed

    private void MenuCadBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadBibliotecaActionPerformed
        abrirTela(new ifrmCadBiblioteca().getClass());
    }//GEN-LAST:event_MenuCadBibliotecaActionPerformed

    private void MenuCadClasLiterariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadClasLiterariasActionPerformed
        abrirTela(new ifrmCadClasLiteraria().getClass());
    }//GEN-LAST:event_MenuCadClasLiterariasActionPerformed

    private void MenuCadEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadEditorasActionPerformed
        abrirTela(new ifrmCadEditora().getClass());
    }//GEN-LAST:event_MenuCadEditorasActionPerformed

    private void MenuCadGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadGruposActionPerformed
        abrirTela(new ifrmCadGrupo().getClass());
    }//GEN-LAST:event_MenuCadGruposActionPerformed

    private void MenuCadIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadIdiomasActionPerformed
        abrirTela(new ifrmCadIdioma().getClass());
    }//GEN-LAST:event_MenuCadIdiomasActionPerformed

    private void MenuCadLeitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadLeitoresActionPerformed
        abrirTela(new ifrmCadLeitores().getClass());
    }//GEN-LAST:event_MenuCadLeitoresActionPerformed

    private void MenuRelatorioAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioAutoresActionPerformed

        try {
            //Connection con = new ConexaoMySQL().getConnection();
            DB banco = new DB();
            banco.connect();

            HashMap parametros = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "RelacaoGeraldeAutores.jasper", parametros, banco.conn);
            JasperViewer jrv = new JasperViewer(jp, false);
            //Maximiza o relatório
            jrv.setExtendedState(MAXIMIZED_BOTH);
            jrv.setVisible(true);
            jrv.setFitPageZoomRatio();
            banco.disconnect();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, e.getCause());
//            e.printStackTrace();
        }




    }//GEN-LAST:event_MenuRelatorioAutoresActionPerformed

    private void MenuRelatorioClasLiterariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioClasLiterariasActionPerformed
        // TODO add your handling code here:
        try {
            DB banco = new DB();
            banco.connect();

            HashMap parametros = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "RelacaoGeraldeClasLiterarias.jasper", parametros, banco.conn);
            JasperViewer jrv = new JasperViewer(jp, false);//false significa que não fecha tudo
            //Maximiza o relatório
            jrv.setExtendedState(MAXIMIZED_BOTH);
//            jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jrv.setVisible(true);
            jrv.setFitPageZoomRatio();
            banco.disconnect();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_MenuRelatorioClasLiterariasActionPerformed

    private void MenuRelatorioEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioEditorasActionPerformed
        // TODO add your handling code here:
        try {

            DB banco = new DB();
            banco.connect();
            HashMap parametros = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "RelacaoGeraldeEditoras.jasper", parametros, banco.conn);
            JasperViewer jrv = new JasperViewer(jp, false);
            //Maximiza o relatório
            jrv.setExtendedState(MAXIMIZED_BOTH);
//            jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jrv.setVisible(true);
            jrv.setFitPageZoomRatio();
            banco.disconnect();

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_MenuRelatorioEditorasActionPerformed

    private void MenuRelatorioGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioGruposActionPerformed

        try {
            DB banco = new DB();
            banco.connect();
            HashMap parametros = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "RelacaoGeraldeGrupos.jasper", parametros, banco.conn);
            JasperViewer jrv = new JasperViewer(jp, false);
            Dimension frameSize = getSize();

            int h = (int) frameSize.getHeight();
            int w = (int) frameSize.getWidth();
            //Maximiza o relatório
            jrv.setExtendedState(MAXIMIZED_BOTH);
//            jrv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jrv.setVisible(true);
            jrv.setFitPageZoomRatio();
            banco.disconnect();

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_MenuRelatorioGruposActionPerformed

    @SuppressWarnings("static-access")
    private void MenuRelatorioLeitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioLeitoresActionPerformed

        try {
            DB banco = new DB();
            banco.connect();

            HashMap parametros = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "RelacaoGeraldeLeitores.jasper", parametros, banco.conn);
            JasperViewer jrv = new JasperViewer(jp, false);
            //Maximiza o relatório
            jrv.setExtendedState(MAXIMIZED_BOTH);
            jrv.setVisible(true);
            jrv.setFitPageZoomRatio();
            banco.disconnect();

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_MenuRelatorioLeitoresActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

//Lê as permissões do usuário e desativa os menus não permitidos   
//        //Login-----------------------------------------------------------------
//        if (cadlogin1 == false) {
//            MenuLoginCadastrarLogin.setVisible(false);
//        }
//        if (cadniveis == false) {
//            MenuLoginCadastrarNiveis.setVisible(false);
//        }
//        //----Cadastros---------------------------------------------------------
//        if (cadcategoriadoleitor == false) {
//            MenuCadCategoriadoLeitor.setVisible(false);
//        }
//        if (cadacervo == false) {
//            MenuCadItens.setVisible(false);
//        }
//        if (cadautores == false) {
//            MenuCadAutor.setVisible(false);
//        }
//        if (cadbiblioteca == false) {
//            MenuCadBiblioteca.setVisible(false);
//        }
//        if (cadclasliteraria == false) {
//            MenuCadClasLiterarias.setVisible(false);
//        }
//        if (cadeditora == false) {
//            MenuCadEditoras.setVisible(false);
//        }
//        if (cadgrupo == false) {
//            MenuCadGrupos.setVisible(false);
//        }
//        if (cadidioma == false) {
//            MenuCadIdiomas.setVisible(false);
//        }
//        if (cadestadodeconservacao == false) {
//            MenuCadEstadodoLivro.setVisible(false);
//        }
//        if (cadleitor == false) {
//            MenuCadLeitores.setVisible(false);
//        }
//        if (cadformacaoacademica == false) {
//            MenuCadFormacaoAcademica.setVisible(false);
//        }
//        if (cadniveldeescolaridade == false) {
//            MenuCadNiveldeEscolaridade.setVisible(false);
//        }
//        if (cadtipodeformacao == false) {
//            MenuCadTipodeFormacao.setVisible(false);
//        }
//        if (cadcidade == false) {
//            MenuCadCidades.setVisible(false);
//        }
//        if (cadbairro == false) {
//            MenuCadBairros.setVisible(false);
//        }
//        //----Movimentação------------------------------------------------------
//        if (movemprestimo == false) {
//            MenuMovimentoEmprestimo.setVisible(false);
//        }
//        if (movdevolucao == false) {
//            MenuMovimentoDevolucao.setVisible(false);
//        }
//        if (movrenovacao == false) {
//            MenuMovimentoRenovacao.setVisible(false);
//        }
//        if (movreserva == false) {
//            MenuMovimentoReserva.setVisible(false);
//        }
//        //----Relatórios--------------------------------------------------------
//        if (relautores == false) {
//            MenuRelatorioAutores.setVisible(false);
//        }
//        if (relclasliterarias == false) {
//            MenuRelatorioClasLiterarias.setVisible(false);
//        }
//        if (releditoras == false) {
//            MenuRelatorioEditoras.setVisible(false);
//        }
//        if (relgrupos == false) {
//            MenuRelatorioGrupos.setVisible(false);
//        }
//        if (relleitores == false) {
//            MenuRelatorioLeitores.setVisible(false);
//        }
//        if (relleituras == false) {
//            MenuRelatorioLeituras.setVisible(false);
//        }
//        if (relemprestimos == false) {
//            MenuRelatorioEmprestimos.setVisible(false);
//        }
//        if (reltitulosmaislidos == false) {
//            MenuRelatorioTitulosMaisLidos.setVisible(false);
//        }
//         if (reltitulosmaisemprestados == false) {
//            MenuRelatorioTitulosMaisEmprestados.setVisible(false);
//        }
//        if (relcarteirinhadoleitor == false) {
//            MenuRelatorioCarteirinhaLeitor.setVisible(false);
//        }
//        if (reletiquetasdasobras1 == false) {
//            MenuRelatorioCodigodeBarrasdasObras.setVisible(false);
//        }
//        if (relobrasdoacervo == false) {
//            MenuRelatorioObras.setVisible(false);
//        }
//        //----Configurações-----------------------------------------------------
//        if (confconfiguracoesgerais == false) {
//            MenuConfigConfiguracoes.setVisible(false);
//        }
//        if (confbackup == false) {
//            MenuConfigBackup.setVisible(false);
//        }
//        if (confrestaurarbackup == false) {
//            MenuConfigRestaurarBackup.setVisible(false);
//        }
//        if (confmudaraparencia == false) {
//            MenuConfigAparencia.setVisible(false);
//        }
//        if (confimagemdefundodomenu == false) {
//            MenuConfigImagemdeFundo.setVisible(false);
//        }
//        //----Ajuda-------------------------------------------------------------
//        if (ajconteudo == false) {
//            MenuAjudaConteudo.setVisible(false);
//        }
////Exclui as reservas que excederam a data=======================================
//        DB banco = new DB();
//        banco.connect();
//        Query query1 = new Query(banco.conn);
//        java.util.Date data = new java.util.Date();
//        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
//        query1.execute("DELETE FROM reservas WHERE validadereserva<'" + df.format(data) + "'");
//        banco.disconnect();
////******************************************************************************
////Menu maximizado
//        setExtendedState(MAXIMIZED_BOTH);
//        try {
////            if (visualizacao == false) {
//            imagemFundo = new ImageIcon("Imagem.jpg").getImage();
//            lblImagem.setIcon(new ImageIcon(imagemFundo.getScaledInstance(screenSize.width, screenSize.height - 50, Image.SCALE_DEFAULT)));
//            lblImagem.setVisible(true);
//            lblImagem.setSize(screenSize.width, screenSize.height - 50);
//            desktopPane.add(lblImagem);
//            this.repaint();
////            }
//////            else {
//////                imagemFundo = new ImageIcon(caminhoImagemFundo).getImage();
//////                lblImagem.setIcon(new ImageIcon(imagemFundo.getScaledInstance(screenSize.width, screenSize.height - 21, Image.SCALE_DEFAULT)));
//////                lblImagem.setVisible(true);
//////                lblImagem.setSize(screenSize.width, screenSize.height - 21);
//////                desktopPane.add(lblImagem);
//////                this.repaint();
//////            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Imagem não encontrada!\n" + e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//          Image icone = Toolkit.getDefaultToolkit().getImage("Icones/Adicionar.png");
//         this.setIconImage(icone);
    }//GEN-LAST:event_formWindowActivated

    private void MenuRelatorioCarteirinhaLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioCarteirinhaLeitorActionPerformed

        abrirTela(new ifrmCarteirinhadoLeitor().getClass());

    }//GEN-LAST:event_MenuRelatorioCarteirinhaLeitorActionPerformed

    private void MenuMovimentoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMovimentoEmprestimoActionPerformed
        abrirTela(new ifrmEmprestimo().getClass());
    }//GEN-LAST:event_MenuMovimentoEmprestimoActionPerformed

    private void MenuMovimentoDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMovimentoDevolucaoActionPerformed
        abrirTela(new ifrmDevolucao().getClass());
    }//GEN-LAST:event_MenuMovimentoDevolucaoActionPerformed

    private void MenuMovimentoRenovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMovimentoRenovacaoActionPerformed
        abrirTela(new ifrmRenovacao().getClass());
    }//GEN-LAST:event_MenuMovimentoRenovacaoActionPerformed

    private void MenuMovimentoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMovimentoReservaActionPerformed
        abrirTela(new ifrmReserva().getClass());
    }//GEN-LAST:event_MenuMovimentoReservaActionPerformed

    private void MenuConfigAparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfigAparenciaActionPerformed
        abrirTela(new ifrmAparencia().getClass());
    }//GEN-LAST:event_MenuConfigAparenciaActionPerformed

    private void MenuAjudaSobreoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudaSobreoSistemaActionPerformed

        abrirTela(new ifrmSobreoSistema().getClass());

    }//GEN-LAST:event_MenuAjudaSobreoSistemaActionPerformed

    private void MenuCadEstadodoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadEstadodoLivroActionPerformed
        abrirTela(new ifrmCadEstadodoLivro().getClass());
    }//GEN-LAST:event_MenuCadEstadodoLivroActionPerformed

    private void MenuCadCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadCidadesActionPerformed
        abrirTela(new ifrmCadCidades().getClass());
    }//GEN-LAST:event_MenuCadCidadesActionPerformed

    private void MenuCadBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadBairrosActionPerformed
        abrirTela(new ifrmCadBairros().getClass());
    }//GEN-LAST:event_MenuCadBairrosActionPerformed

    private void MenuRelatorioCodigodeBarrasdasObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioCodigodeBarrasdasObrasActionPerformed
        abrirTela(new ifrmEtiquetascomCodigodeBarras().getClass());
    }//GEN-LAST:event_MenuRelatorioCodigodeBarrasdasObrasActionPerformed

    private void MenuConfigConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfigConfiguracoesActionPerformed
        abrirTela(new ifrmConfiguracoes().getClass());
    }//GEN-LAST:event_MenuConfigConfiguracoesActionPerformed

    private void MenuCadFormacaoAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadFormacaoAcademicaActionPerformed
        abrirTela(new ifrmCadFormacaoAcademica().getClass());
    }//GEN-LAST:event_MenuCadFormacaoAcademicaActionPerformed

    private void MenuCadNiveldeEscolaridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadNiveldeEscolaridadeActionPerformed
        abrirTela(new ifrmCadNiveldeEscolaridade().getClass());
    }//GEN-LAST:event_MenuCadNiveldeEscolaridadeActionPerformed

    private void MenuCadTipodeFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadTipodeFormacaoActionPerformed
        abrirTela(new ifrmCadTipodeFormacao().getClass());
    }//GEN-LAST:event_MenuCadTipodeFormacaoActionPerformed

    private void MenuConfigImagemdeFundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfigImagemdeFundoActionPerformed
        abrirTela(new ifrmImagemdeFundo().getClass());
    }//GEN-LAST:event_MenuConfigImagemdeFundoActionPerformed

    private void MenuRelatorioEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioEmprestimosActionPerformed
        abrirTela(new ifrmRelatorioEmprestimos().getClass());
    }//GEN-LAST:event_MenuRelatorioEmprestimosActionPerformed

    private void MenuRelatorioLeiturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioLeiturasActionPerformed
        abrirTela(new ifrmRelatorioLeituraNoLocal().getClass());
    }//GEN-LAST:event_MenuRelatorioLeiturasActionPerformed

    private void MenuRelatorioTitulosMaisLidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioTitulosMaisLidosActionPerformed
        abrirTela(new ifrmRelatorioTitulosMaisLidos().getClass());
    }//GEN-LAST:event_MenuRelatorioTitulosMaisLidosActionPerformed

    private void MenuRelatorioTitulosMaisEmprestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioTitulosMaisEmprestadosActionPerformed
        abrirTela(new ifrmRelatorioTitulosMaisEmprestados().getClass());
    }//GEN-LAST:event_MenuRelatorioTitulosMaisEmprestadosActionPerformed

    private void MenuRelatorioObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioObrasActionPerformed
        abrirTela(new ifrmRelatorioObras().getClass());
    }//GEN-LAST:event_MenuRelatorioObrasActionPerformed

    private void MenuConfigBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfigBackupActionPerformed
        abrirTela(new ifrmBackup().getClass());
    }//GEN-LAST:event_MenuConfigBackupActionPerformed

    private void MenuConfigRestaurarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConfigRestaurarBackupActionPerformed
        abrirTela(new ifrmRestaurarBackup().getClass());
    }//GEN-LAST:event_MenuConfigRestaurarBackupActionPerformed

    private void desktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopPaneMouseClicked
        if (evt.getClickCount() == 1) {
            menuBar.setVisible(false);
        } else if (evt.getClickCount() == 2) {
            menuBar.setVisible(true);
        }
    }//GEN-LAST:event_desktopPaneMouseClicked

    private void MenuLoginLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginLogoutActionPerformed
        this.setVisible(false);
        this.dispose();
        new frmLogin().setVisible(true);

    }//GEN-LAST:event_MenuLoginLogoutActionPerformed

    private void MenuLoginCadastrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginCadastrarLoginActionPerformed
        abrirTela(new ifrmCadLogin().getClass());
    }//GEN-LAST:event_MenuLoginCadastrarLoginActionPerformed

    private void MenuLoginCadastrarNiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginCadastrarNiveisActionPerformed
        abrirTela(new ifrmCadNiveis().getClass());
    }//GEN-LAST:event_MenuLoginCadastrarNiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmMenu().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenuItem MenuAjudaConteudo;
    private javax.swing.JMenuItem MenuAjudaSobreoSistema;
    private javax.swing.JMenuItem MenuCadAutor;
    private javax.swing.JMenuItem MenuCadBairros;
    private javax.swing.JMenuItem MenuCadBiblioteca;
    private javax.swing.JMenuItem MenuCadCategoriadoLeitor;
    private javax.swing.JMenuItem MenuCadCidades;
    private javax.swing.JMenuItem MenuCadClasLiterarias;
    private javax.swing.JMenuItem MenuCadEditoras;
    private javax.swing.JMenuItem MenuCadEstadodoLivro;
    private javax.swing.JMenuItem MenuCadFormacaoAcademica;
    private javax.swing.JMenuItem MenuCadGrupos;
    private javax.swing.JMenuItem MenuCadIdiomas;
    private javax.swing.JMenuItem MenuCadItens;
    private javax.swing.JMenuItem MenuCadLeitores;
    private javax.swing.JMenuItem MenuCadNiveldeEscolaridade;
    private javax.swing.JMenuItem MenuCadTipodeFormacao;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JMenuItem MenuConfigAparencia;
    private javax.swing.JMenuItem MenuConfigBackup;
    private javax.swing.JMenuItem MenuConfigConfiguracoes;
    private javax.swing.JMenuItem MenuConfigImagemdeFundo;
    private javax.swing.JMenuItem MenuConfigRestaurarBackup;
    private javax.swing.JMenu MenuLogin;
    private javax.swing.JMenuItem MenuLoginCadastrarLogin;
    private javax.swing.JMenuItem MenuLoginCadastrarNiveis;
    private javax.swing.JMenuItem MenuLoginLogout;
    private javax.swing.JMenu MenuMovimentacao;
    private javax.swing.JMenuItem MenuMovimentoDevolucao;
    private javax.swing.JMenuItem MenuMovimentoEmprestimo;
    private javax.swing.JMenuItem MenuMovimentoRenovacao;
    private javax.swing.JMenuItem MenuMovimentoReserva;
    private javax.swing.JMenuItem MenuRelatorioAutores;
    private javax.swing.JMenuItem MenuRelatorioCarteirinhaLeitor;
    private javax.swing.JMenuItem MenuRelatorioClasLiterarias;
    private javax.swing.JMenuItem MenuRelatorioCodigodeBarrasdasObras;
    private javax.swing.JMenuItem MenuRelatorioEditoras;
    private javax.swing.JMenuItem MenuRelatorioEmprestimos;
    private javax.swing.JMenuItem MenuRelatorioGrupos;
    private javax.swing.JMenuItem MenuRelatorioLeitores;
    private javax.swing.JMenuItem MenuRelatorioLeituras;
    private javax.swing.JMenuItem MenuRelatorioObras;
    private javax.swing.JMenuItem MenuRelatorioTitulosMaisEmprestados;
    private javax.swing.JMenuItem MenuRelatorioTitulosMaisLidos;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
