/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ifrmRelatorioEmprestimos.java
 *
 * Created on 05/04/2011, 10:09:58
 */
package FormsRelatorio;

import FormsConsulta.jdfrmConsultaLeitores;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.HashMap;
import javax.swing.JOptionPane;
import Classes.DB;
import Classes.FixedLengthDocument;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARK
 */
public class ifrmRelatorioEmprestimos extends javax.swing.JInternalFrame {

    private DB banco;

    /** Creates new form ifrmRelatorioEmprestimos */
    public ifrmRelatorioEmprestimos() {
        initComponents();
        txtDataInicial.setDocument(new FixedLengthDocument(10));
        txtDataFinal.setDocument(new FixedLengthDocument(10));
        txtCodigo.setDocument(new FixedLengthDocument(10));
        txtDescricao.setDocument(new FixedLengthDocument(50));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdPorPeriodo = new javax.swing.JRadioButton();
        rdPorCodLeitor = new javax.swing.JRadioButton();
        rdPorNome = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtDataInicial = new javax.swing.JTextField();
        txtDataFinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnConsultaNomeLeitor = new javax.swing.JButton();
        btnConsultaCodLeitor = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rdAsc = new javax.swing.JRadioButton();
        rdDesc = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rdOrdemData = new javax.swing.JRadioButton();
        rdOrdemCodLeitor = new javax.swing.JRadioButton();
        rdOrdemNome = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Relatório de Empréstimos");
        setMaximumSize(new java.awt.Dimension(624, 375));
        setMinimumSize(new java.awt.Dimension(624, 375));
        setPreferredSize(new java.awt.Dimension(624, 375));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opções de Relatório:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroup1.add(rdPorPeriodo);
        rdPorPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorPeriodo.setText("Por Período");
        rdPorPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorPeriodoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPorCodLeitor);
        rdPorCodLeitor.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorCodLeitor.setText("Por Código do Leitor");
        rdPorCodLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorCodLeitorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPorNome);
        rdPorNome.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorNome.setText("Por Nome do Leitor");
        rdPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorNomeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(rdPorPeriodo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdPorCodLeitor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdPorNome)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rdPorPeriodo)
                    .add(rdPorCodLeitor)
                    .add(rdPorNome))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), ":", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtDataInicial.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtDataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyTyped(evt);
            }
        });

        txtDataFinal.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtDataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataFinalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDataFinalKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Data Inicial:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Data Final:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Código:");

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Nome:");

        btnConsultaNomeLeitor.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnConsultaNomeLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Procurar16x16.png"))); // NOI18N
        btnConsultaNomeLeitor.setPreferredSize(new java.awt.Dimension(49, 21));
        btnConsultaNomeLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaNomeLeitorActionPerformed(evt);
            }
        });

        btnConsultaCodLeitor.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnConsultaCodLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Procurar16x16.png"))); // NOI18N
        btnConsultaCodLeitor.setPreferredSize(new java.awt.Dimension(49, 21));
        btnConsultaCodLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCodLeitorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel3)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtDataInicial, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(btnConsultaCodLeitor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtDataFinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(txtDescricao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnConsultaNomeLeitor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(btnConsultaCodLeitor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtDataInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtDataFinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnConsultaNomeLeitor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtDescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel4)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/VRelatorio.png"))); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ordem:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroup3.add(rdAsc);
        rdAsc.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdAsc.setText("Ascendente");

        buttonGroup3.add(rdDesc);
        rdDesc.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdDesc.setText("Descendente");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(rdAsc)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdDesc)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rdAsc)
                    .add(rdDesc))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ordenar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroup2.add(rdOrdemData);
        rdOrdemData.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdOrdemData.setText("Data");

        buttonGroup2.add(rdOrdemCodLeitor);
        rdOrdemCodLeitor.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdOrdemCodLeitor.setText("Código do Leitor");

        buttonGroup2.add(rdOrdemNome);
        rdOrdemNome.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdOrdemNome.setText("Nome do Leitor");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(rdOrdemData)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdOrdemCodLeitor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdOrdemNome)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rdOrdemData)
                    .add(rdOrdemCodLeitor)
                    .add(rdOrdemNome))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnVisualizar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnVisualizar)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-624)/2, (screenSize.height-375)/2, 624, 375);
    }// </editor-fold>//GEN-END:initComponents

//Ler arquivo texto
    private String CaminhodoRelatorio() {
        String caminho = null;
        try {
            FileReader reader = new FileReader(new File("config.txt"));
            BufferedReader leitor = new BufferedReader(reader);

            //Lê linha por linha \n quebra a linha
            leitor.readLine().substring(8);
            leitor.readLine().substring(12);
            caminho = leitor.readLine().substring(12);

            //Fecha a leitura
            reader.close();
            leitor.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return caminho;
    }

    private void rdPorPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorPeriodoActionPerformed
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        txtDataInicial.setVisible(true);
        txtDataFinal.setVisible(true);
        txtCodigo.setVisible(false);
        txtDescricao.setVisible(false);
        btnConsultaNomeLeitor.setVisible(false);
        btnConsultaCodLeitor.setVisible(false);
        txtDataInicial.requestFocus();
    }//GEN-LAST:event_rdPorPeriodoActionPerformed

    private void rdPorCodLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorCodLeitorActionPerformed
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        txtDataInicial.setVisible(false);
        txtDataFinal.setVisible(false);
        txtCodigo.setVisible(true);
        txtDescricao.setVisible(false);
        btnConsultaNomeLeitor.setVisible(false);
        btnConsultaCodLeitor.setVisible(true);
        txtCodigo.requestFocus();
    }//GEN-LAST:event_rdPorCodLeitorActionPerformed

    private void rdPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorNomeActionPerformed
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        txtDataInicial.setVisible(false);
        txtDataFinal.setVisible(false);
        txtCodigo.setVisible(false);
        txtDescricao.setVisible(true);
        btnConsultaNomeLeitor.setVisible(true);
        btnConsultaCodLeitor.setVisible(false);
        txtDescricao.requestFocus();
    }//GEN-LAST:event_rdPorNomeActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed

        banco = new DB();
        banco.connect();
        HashMap parametros = new HashMap();
        String sql = null;
        String titulo = null;
        String ordenar = null;
        String ordem = null;
        boolean ok = false;

        //Verificação >Ordenar por:
        if (rdOrdemData.isSelected()) {
            ordenar = "m.data_2 ";
        } else if (rdOrdemCodLeitor.isSelected()) {
            ordenar = "m.codleitor ";
        } else if (rdOrdemNome.isSelected()) {
            ordenar = "l.nomedoleitor ";
        }
        //Verificação >Ordem:
        if (rdAsc.isSelected()) {
            ordem = "ASC";
        } else {
            ordem = "DESC";
        }
        //verificação Opções de Relatório
        if (rdPorPeriodo.isSelected()) {
            titulo = "Relação de Empréstimos no período de "
                    + txtDataInicial.getText().trim() + " a " + txtDataFinal.getText().trim();
            sql = "SELECT m.codigo,m.data_2,m.hora,m.codleitor,l.nomedoleitor"
                    + " FROM movimento m"
                    + " INNER JOIN cadleitores l ON m.codleitor = l.codigo"
                    + " WHERE m.data_2 BETWEEN '" + txtDataInicial.getText()
                    + "' AND '" + txtDataFinal.getText() + "'"
                    + " ORDER BY " + ordenar + ordem;
        } else if (rdPorCodLeitor.isSelected()) {
            titulo = "Relação de Empréstimos do Leitor nº " + txtCodigo.getText().trim();
            sql = "SELECT m.codigo,m.data_2,m.hora,m.codleitor,l.nomedoleitor"
                    + " FROM movimento m"
                    + " INNER JOIN cadleitores l ON m.codleitor = l.codigo"
                    + " WHERE m.codleitor=" + txtCodigo.getText().trim()
                    + " ORDER BY " + ordenar + ordem;
        } else if (rdPorNome.isSelected()) {
            titulo = "Relação de Empréstimos do(a) Leitor(a) " + txtDescricao.getText().trim();
            sql = "SELECT m.codigo,m.data_2,m.hora,m.codleitor,l.nomedoleitor"
                    + " FROM movimento m"
                    + " INNER JOIN cadleitores l ON m.codleitor = l.codigo"
                    + " WHERE l.nomedoleitor='" + txtDescricao.getText().trim() + "'"
                    + " ORDER BY " + ordenar + ordem;
        }
//------------VALIDAÇÃO---------------------------------------------------------
        if (rdPorPeriodo.isSelected()) {
            if (txtDataInicial.getText().trim().equals("") || txtDataInicial.getText().trim().length() < 10) {
                JOptionPane.showMessageDialog(null, "A data inicial não pode ser nula ou menor que 10 caracteres !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtDataInicial.requestFocus();
            } else if (txtDataFinal.getText().trim().equals("") || txtDataFinal.getText().trim().length() < 10) {
                JOptionPane.showMessageDialog(null, "A data final não pode ser nula ou menor que 10 caracteres !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtDataFinal.requestFocus();
            }
            if (!txtDataInicial.getText().trim().equals("")
                    && txtDataInicial.getText().trim().length() == 10
                    && txtDataFinal.getText().trim().equals("")
                    && txtDataFinal.getText().trim().length() == 10) {
                ok = true;
            }
        } else if (rdPorCodLeitor.isSelected()) {
            if (txtCodigo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o código do leitor !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtCodigo.requestFocus();
            }
            if (!txtCodigo.getText().trim().equals("")) {
                ok = true;
            }
        } else if (rdPorNome.isSelected()) {
            if (txtDescricao.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o nome do leitor !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtDescricao.requestFocus();
            }
            if (!txtDescricao.getText().trim().equals("")) {
                ok = true;
            }
        }
//------------------------------------------------------------------------------
        if (ok == true) {
            try {
                parametros.put("pSQL", sql);
                parametros.put("pTitulo", titulo);
                //C:\\Users\\MARK\\Documents\\NetBeansProjects\\Login\\Relatorios\\
                JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "REmp.jasper", parametros, banco.conn);
                JasperViewer jrv = new JasperViewer(jp, false);
                //Para maximizar o relatório
                Toolkit tk = Toolkit.getDefaultToolkit();
                Dimension screenSize = tk.getScreenSize();
                //Maximiza o relatório
                jrv.setSize(screenSize.width, screenSize.height);
                jrv.setLocation(0, 0);
                jrv.setTitle(titulo);
                jrv.setVisible(true);
                jrv.setFitPageZoomRatio();
                banco.disconnect();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro " + e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void txtDataInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDataInicialKeyTyped

    private void txtDataFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFinalKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDataFinalKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnConsultaNomeLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNomeLeitorActionPerformed
        jdfrmConsultaLeitores cl = new jdfrmConsultaLeitores(null, closable);
        cl.setVisible(true);
        cl.toFront();
        if (cl.okSelecionado == true) {
            txtDescricao.setText(cl.getNome());
            txtDescricao.requestFocus();
            cl.setVisible(false);
            cl.dispose();
        }
}//GEN-LAST:event_btnConsultaNomeLeitorActionPerformed

    private void txtDataInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyReleased
        switch (txtDataInicial.getText().trim().length()) {
            case 2:
                txtDataInicial.setText(txtDataInicial.getText().trim() + "/");
                break;
            case 5:
                txtDataInicial.setText(txtDataInicial.getText().trim() + "/");
                break;
        }
    }//GEN-LAST:event_txtDataInicialKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        rdPorPeriodo.setSelected(true);
        rdOrdemData.setSelected(true);
        rdAsc.setSelected(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        txtDataInicial.setVisible(true);
        txtDataFinal.setVisible(true);
        txtCodigo.setVisible(false);
        txtDescricao.setVisible(false);
        btnConsultaNomeLeitor.setVisible(false);
        btnConsultaCodLeitor.setVisible(false);
        txtDataInicial.requestFocus();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtDataFinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFinalKeyReleased
        switch (txtDataFinal.getText().trim().length()) {
            case 2:
                txtDataFinal.setText(txtDataFinal.getText().trim() + "/");
                break;
            case 5:
                txtDataFinal.setText(txtDataFinal.getText().trim() + "/");
                break;
        }
    }//GEN-LAST:event_txtDataFinalKeyReleased

    private void btnConsultaCodLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCodLeitorActionPerformed
        jdfrmConsultaLeitores cl = new jdfrmConsultaLeitores(null, closable);
        cl.setVisible(true);
        cl.toFront();
        if (cl.okSelecionado == true) {
            txtCodigo.setText(cl.getCodigo());
            txtCodigo.requestFocus();
            cl.setVisible(false);
            cl.dispose();
        }
    }//GEN-LAST:event_btnConsultaCodLeitorActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaCodLeitor;
    private javax.swing.JButton btnConsultaNomeLeitor;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rdAsc;
    private javax.swing.JRadioButton rdDesc;
    private javax.swing.JRadioButton rdOrdemCodLeitor;
    private javax.swing.JRadioButton rdOrdemData;
    private javax.swing.JRadioButton rdOrdemNome;
    private javax.swing.JRadioButton rdPorCodLeitor;
    private javax.swing.JRadioButton rdPorNome;
    private javax.swing.JRadioButton rdPorPeriodo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtDataInicial;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
