/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ifrmRelatorioEmprestimos.java
 *
 * Created on 05/04/2011, 10:09:58
 */
package FormsRelatorio;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.HashMap;
import javax.swing.JOptionPane;
import Classes.DB;
import FormsConsulta.jdfrmConsultaAcervodeObras;
import FormsConsulta.jdfrmConsultaClasLiteraria;
import FormsConsulta.jdfrmConsultaEditora;
import FormsConsulta.jdfrmConsultaGrupo;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARK
 */
public class ifrmRelatorioObras extends javax.swing.JInternalFrame {

//    private DB banco;
    /** Creates new form ifrmRelatorioEmprestimos */
    public ifrmRelatorioObras() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdGeral = new javax.swing.JRadioButton();
        rdPorTitulo = new javax.swing.JRadioButton();
        rdPorClasLiteraria = new javax.swing.JRadioButton();
        rdPorGrupo = new javax.swing.JRadioButton();
        rdPorEditora = new javax.swing.JRadioButton();
        btnVisualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rdAsc = new javax.swing.JRadioButton();
        rdDesc = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        btnConsultaObra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClasLiteraria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        btnConsultaClasLiteraria = new javax.swing.JButton();
        btnConsultaGrupo = new javax.swing.JButton();
        btnConsultaEditora = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Relação de Obras");
        setMaximumSize(new java.awt.Dimension(440, 313));
        setMinimumSize(new java.awt.Dimension(440, 313));
        setPreferredSize(new java.awt.Dimension(440, 313));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opções de Relatório:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroup1.add(rdGeral);
        rdGeral.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdGeral.setText("Geral");
        rdGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGeralActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPorTitulo);
        rdPorTitulo.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorTitulo.setText("Por Título");
        rdPorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorTituloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPorClasLiteraria);
        rdPorClasLiteraria.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorClasLiteraria.setText("Por Classificação Literária");
        rdPorClasLiteraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorClasLiterariaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPorGrupo);
        rdPorGrupo.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorGrupo.setText("Grupo");
        rdPorGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorGrupoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdPorEditora);
        rdPorEditora.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdPorEditora.setText("Por Editora");
        rdPorEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPorEditoraActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rdGeral)
                    .add(rdPorGrupo))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(rdPorTitulo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rdPorClasLiteraria))
                    .add(rdPorEditora))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rdGeral)
                    .add(rdPorClasLiteraria)
                    .add(rdPorTitulo))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rdPorGrupo)
                    .add(rdPorEditora))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/VRelatorio.png"))); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ordem:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttonGroup2.add(rdAsc);
        rdAsc.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdAsc.setText("Ascendente");

        buttonGroup2.add(rdDesc);
        rdDesc.setFont(new java.awt.Font("Tahoma", 0, 14));
        rdDesc.setText("Descendente");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rdAsc)
                    .add(rdDesc))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(rdAsc)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rdDesc)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnConsultaObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Procurar16x16.png"))); // NOI18N
        btnConsultaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaObraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Título:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Clas.Literária:");

        txtClasLiteraria.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Grupo:");

        txtGrupo.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Editora:");

        txtEditora.setFont(new java.awt.Font("Tahoma", 0, 14));

        btnConsultaClasLiteraria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Procurar16x16.png"))); // NOI18N
        btnConsultaClasLiteraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaClasLiterariaActionPerformed(evt);
            }
        });

        btnConsultaGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Procurar16x16.png"))); // NOI18N
        btnConsultaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaGrupoActionPerformed(evt);
            }
        });

        btnConsultaEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Procurar16x16.png"))); // NOI18N
        btnConsultaEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaEditoraActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtEditora, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jLabel1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(txtTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btnConsultaObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jLabel2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(txtClasLiteraria, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnConsultaClasLiteraria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtGrupo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnConsultaGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnConsultaEditora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(btnConsultaEditora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(btnConsultaGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(btnConsultaClasLiteraria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(btnConsultaObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                .add(txtTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(jLabel1)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(txtClasLiteraria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel2))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(txtGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel3))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtEditora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(btnCancelar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnVisualizar))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnVisualizar)
                    .add(btnCancelar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-535)/2, (screenSize.height-353)/2, 535, 353);
    }// </editor-fold>//GEN-END:initComponents

//Ler arquivo texto
    private String CaminhodoRelatorio() {
        String caminho = null;
        try {
            FileReader reader = new FileReader(new File("config.txt"));
            BufferedReader leitor = new BufferedReader(reader);

            //Lê linha por linha \n quebra a linha
            leitor.readLine().substring(8);
            leitor.readLine().substring(12);
            caminho = leitor.readLine().substring(12);

            //Fecha a leitura
            reader.close();
            leitor.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return caminho;
    }

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed

        DB banco = new DB();
        banco.connect();
        HashMap parametros = new HashMap();
        String sql = null;
        String titulo = null;
        String ordem = null;
        boolean ok = false;

        //Verificação >Ordem:
        if (rdAsc.isSelected()) {
            ordem = "ASC";
        } else {
            ordem = "DESC";
        }
        //Verifica Opções de Relatório
        if (rdGeral.isSelected()) {
            sql = "SELECT c.codigo,c.titulo,c.local_2"
                    + " FROM cadlivros c"
                    + " ORDER BY c.titulo " + ordem;
            titulo = "Relação Geral de Obras do Acervo";
        } else if (rdPorTitulo.isSelected()) {
            sql = "SELECT c.codigo,c.titulo,c.local_2"
                    + " FROM cadlivros c"
                    + " WHERE c.titulo='" + txtTitulo.getText().trim() + "'"
                    + " ORDER BY c.titulo " + ordem;
            titulo = "Relação de Exemplares do Título " + txtTitulo.getText().trim();
        } else if (rdPorClasLiteraria.isSelected()) {
            sql = "SELECT c.codigo,c.titulo,c.local_2"
                    + " FROM cadlivros c,cadclasliteraria cl"
                    + " WHERE c.codclas_literaria=cl.codigo"
                    + " AND cl.clasliteraria='" + txtClasLiteraria.getText().trim() + "'"
                    + " ORDER BY cl.clasliteraria " + ordem;
            titulo = "Relação de Exemplares da Clas.Literária " + txtClasLiteraria.getText().trim();
        } else if (rdPorGrupo.isSelected()) {
            sql = "SELECT c.codigo,c.titulo,c.local_2"
                    + " FROM cadlivros c,cadgrupos g"
                    + " WHERE c.codgrupo=g.codigo"
                    + " AND g.grupo='" + txtGrupo.getText().trim() + "'"
                    + " ORDER BY g.grupo " + ordem;
            titulo = "Relação de Exemplares do Grupo " + txtGrupo.getText().trim();
        } else if (rdPorEditora.isSelected()) {
            sql = "SELECT c.codigo,c.titulo,c.local_2"
                    + " FROM cadlivros c,cadeditoras e"
                    + " WHERE c.codeditora=e.codigo"
                    + " AND e.editora='" + txtEditora.getText().trim() + "'"
                    + " ORDER BY e.editora " + ordem;
            titulo = "Relação de Exemplares da Editora " + txtEditora.getText().trim();
        }
//------------------------------------------------------------------------------
//Verificar se os campos estão preenchidos
        if (rdGeral.isSelected()) {
            ok = true;
        } else if (rdPorTitulo.isSelected()) {
            if (txtTitulo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o título da Obra !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtTitulo.requestFocus();
            } else if (!txtTitulo.getText().trim().equals("")) {
                ok = true;
            }

        } else if (rdPorClasLiteraria.isSelected()) {
            if (txtClasLiteraria.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite a classificação literária !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtClasLiteraria.requestFocus();
            } else if (!txtClasLiteraria.getText().trim().equals("")) {
                ok = true;
            }
        } else if (rdPorGrupo.isSelected()) {
            if (txtGrupo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o grupo !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtGrupo.requestFocus();
            } else if (!txtGrupo.getText().trim().equals("")) {
                ok = true;
            }
        } else if (rdPorEditora.isSelected()) {
            if (txtEditora.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite a editora !", "Aviso", JOptionPane.WARNING_MESSAGE);
                txtEditora.requestFocus();
            } else if (!txtEditora.getText().trim().equals("")) {
                ok = true;
            }
        }
        if (ok == true) {
            try {
                parametros.put("pSQL", sql);
                parametros.put("pTitulo", titulo);
                JasperPrint jp = JasperFillManager.fillReport(CaminhodoRelatorio() + "RObras.jasper", parametros, banco.conn);
                JasperViewer jrv = new JasperViewer(jp, false);
                //Para maximizar o relatório
                Toolkit tk = Toolkit.getDefaultToolkit();
                Dimension screenSize = tk.getScreenSize();
                //Maximiza o relatório
                jrv.setSize(screenSize.width, screenSize.height);
                jrv.setLocation(0, 0);
                jrv.setTitle(titulo);
                jrv.setVisible(true);
                jrv.setFitPageZoomRatio();
                banco.disconnect();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro " + e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        rdGeral.setSelected(true);
        rdAsc.setSelected(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void rdGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGeralActionPerformed
        jPanel2.setVisible(false);
    }//GEN-LAST:event_rdGeralActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rdPorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorTituloActionPerformed
        jPanel2.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        txtTitulo.setVisible(true);
        txtClasLiteraria.setVisible(false);
        txtGrupo.setVisible(false);
        txtEditora.setVisible(false);
        btnConsultaObra.setVisible(true);
        btnConsultaClasLiteraria.setVisible(false);
        btnConsultaGrupo.setVisible(false);
        btnConsultaEditora.setVisible(false);
    }//GEN-LAST:event_rdPorTituloActionPerformed

    private void rdPorClasLiterariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorClasLiterariaActionPerformed
        jPanel2.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(true);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        txtTitulo.setVisible(false);
        txtClasLiteraria.setVisible(true);
        txtGrupo.setVisible(false);
        txtEditora.setVisible(false);
        btnConsultaObra.setVisible(false);
        btnConsultaClasLiteraria.setVisible(true);
        btnConsultaGrupo.setVisible(false);
        btnConsultaEditora.setVisible(false);
    }//GEN-LAST:event_rdPorClasLiterariaActionPerformed

    private void rdPorGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorGrupoActionPerformed
        jPanel2.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(false);
        txtTitulo.setVisible(false);
        txtClasLiteraria.setVisible(false);
        txtGrupo.setVisible(true);
        txtEditora.setVisible(false);
        btnConsultaObra.setVisible(false);
        btnConsultaClasLiteraria.setVisible(false);
        btnConsultaGrupo.setVisible(true);
        btnConsultaEditora.setVisible(false);
    }//GEN-LAST:event_rdPorGrupoActionPerformed

    private void rdPorEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPorEditoraActionPerformed
        jPanel2.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        txtTitulo.setVisible(false);
        txtClasLiteraria.setVisible(false);
        txtGrupo.setVisible(false);
        txtEditora.setVisible(true);
        btnConsultaObra.setVisible(false);
        btnConsultaClasLiteraria.setVisible(false);
        btnConsultaGrupo.setVisible(false);
        btnConsultaEditora.setVisible(true);
    }//GEN-LAST:event_rdPorEditoraActionPerformed

    private void btnConsultaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaObraActionPerformed
        jdfrmConsultaAcervodeObras cl = new jdfrmConsultaAcervodeObras(null, closable);
        cl.setVisible(true);
        cl.toFront();
        String t=cl.getTitulo();
        if (cl.okSelecionado == true) {
            txtTitulo.setText(t);
            txtTitulo.requestFocus();
            cl.setVisible(false);
            cl.dispose();
        }
        System.out.println(cl.okSelecionado);

    }//GEN-LAST:event_btnConsultaObraActionPerformed

    private void btnConsultaClasLiterariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaClasLiterariaActionPerformed
        jdfrmConsultaClasLiteraria cl = new jdfrmConsultaClasLiteraria(null, closable);
        cl.setVisible(true);
        cl.toFront();
        if (cl.okSelecionado == true) {
            txtClasLiteraria.setText(cl.getNome());
            txtClasLiteraria.requestFocus();
            cl.setVisible(false);
            cl.dispose();
        }
    }//GEN-LAST:event_btnConsultaClasLiterariaActionPerformed

    private void btnConsultaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaGrupoActionPerformed
        jdfrmConsultaGrupo cl = new jdfrmConsultaGrupo(null, closable);
        cl.setVisible(true);
        cl.toFront();
        if (cl.okSelecionado == true) {
            txtGrupo.setText(cl.getNome());
            txtGrupo.requestFocus();
            cl.setVisible(false);
            cl.dispose();
        }
    }//GEN-LAST:event_btnConsultaGrupoActionPerformed

    private void btnConsultaEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaEditoraActionPerformed
        jdfrmConsultaEditora cl = new jdfrmConsultaEditora(null, closable);
        cl.setVisible(true);
        cl.toFront();
        if (cl.okSelecionado == true) {
            txtEditora.setText(cl.getNome());
            txtEditora.requestFocus();
            cl.setVisible(false);
            cl.dispose();
        }
    }//GEN-LAST:event_btnConsultaEditoraActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultaClasLiteraria;
    private javax.swing.JButton btnConsultaEditora;
    private javax.swing.JButton btnConsultaGrupo;
    private javax.swing.JButton btnConsultaObra;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rdAsc;
    private javax.swing.JRadioButton rdDesc;
    private javax.swing.JRadioButton rdGeral;
    private javax.swing.JRadioButton rdPorClasLiteraria;
    private javax.swing.JRadioButton rdPorEditora;
    private javax.swing.JRadioButton rdPorGrupo;
    private javax.swing.JRadioButton rdPorTitulo;
    private javax.swing.JTextField txtClasLiteraria;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
